# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almamatters', '0002_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ImageField(default=b'media/logo.png', help_text=b'Upload College Logo', upload_to=b'static media/'),
        ),
    ]
