# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almamatters', '0003_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(default=b'almamatters/static/media/logo.png', help_text=b'Upload College Logo', upload_to=b'almamatters/static/media/'),
        ),
    ]
