# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almamatters', '0005_auto_20180719_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(help_text=b'Upload College Logo', upload_to=b'static/media/'),
        ),
    ]
