# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almamatters', '0006_auto_20180719_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[(b'engineering', b'Engineering'), (b'management', b'BSchool'), (b'law', b'Law')], max_length=15)),
                ('course', models.CharField(choices=[(b'btech', b'B.Tech'), (b'bba', b'BBA'), (b'llb', b'LLB')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(help_text=b'Upload College Logo', upload_to=b'images'),
        ),
    ]
