# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almamatters', '0007_auto_20180723_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
