# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almamatters', '0010_auto_20180725_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almamatters.Category'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almamatters.Course'),
        ),
    ]
