# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almamatters', '0011_auto_20180725_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
    ]
