# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.IntegerField(unique=True)),
                ('floor_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2018, 7, 5, 18, 55, 5, 384000, tzinfo=utc))),
                ('exit_time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[(b'car', b'Car'), (b'bike', b'Bike')], max_length=15)),
                ('vehicle_no', models.TextField(max_length=30, unique=True)),
                ('owner_m_no', models.CharField(max_length=15)),
                ('slot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_system.Slot')),
            ],
        ),
        migrations.AddField(
            model_name='slip',
            name='s_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_system.Slot'),
        ),
        migrations.AddField(
            model_name='slip',
            name='v_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_veh_no', to='parking_system.VehicleInfo'),
        ),
        migrations.AddField(
            model_name='slip',
            name='v_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_veh_type', to='parking_system.VehicleInfo'),
        ),
        migrations.AddField(
            model_name='floor',
            name='slots',
            field=models.ManyToManyField(to='parking_system.Slot'),
        ),
    ]
