# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
