# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='useremail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='userfirstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='userlastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
