# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180706_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 10, 22, 1, 605000, tzinfo=utc)),
        ),
    ]
