# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180727_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 8, 42, 27, 857000, tzinfo=utc)),
        ),
    ]
